name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # -----------------------------
  # 1. Tests con requirements-test.txt
  # -----------------------------
  test-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias de test (mock)
        run: |
          python3 -m venv env-test
          source env-test/bin/activate
          pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Ejecutar tests sincronizados
        run: |
          source env-test/bin/activate
          pytest -v tests/sync --maxfail=1 --disable-warningsll -r requirements.txt
          pytest
